name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.8.18", "3.9.18", "3.10.17"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint requests pyyaml numpy
        if [ "${{ matrix.python-version }}" = "3.8.18" ]; then
          pip install spidev
        fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
